networks:
  ia-net:
    driver: bridge

services:
  # El Proxy Sidecar de free-claude-code traduciendo a Gemini O NVIDIA NIM
  ia_proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    image: ia-opencode-nvidia-proxy:latest
    pull_policy: build
    container_name: ia_opencode_nvidia_proxy
    networks:
      - ia-net
    ports:
      - "127.0.0.1:8082:8082"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NVIDIA_NIM_API_KEY=${NVIDIA_NIM_API_KEY}
# profundo pero con limite de cuota por minuto mayor entradas por dia
#      - MODEL=gemini/gemini-1.5-pro
#      - MODEL_SONNET=gemini/gemini-1.5-pro
# básico no usar
#      - MODEL=gemini/gemini-3.1-flash-lite
#      - MODEL_SONNET=gemini/gemini-3.1-flash-lite
# mayor cuota por minuto pero menos profundo más perspectiva de contexto
#      - MODEL=gemini/gemini-2.5-flash
#      - MODEL_SONNET=gemini/gemini-2.5-flash
# mayor entradas por dia
#      - MODEL=gemini/gemini-2.5-pro
#      - MODEL_SONNET=gemini/gemini-2.5-pro
#      - MODEL=gemini/gemini-2.0-flash
#      - MODEL_SONNET=gemini/gemini-2.0-flash
      - MODEL=nvidia_nim/meta/llama-3.3-70b-instruct
      - MODEL_SONNET=nvidia_nim/meta/llama-3.3-70b-instruct
#      - MODEL=nvidia_nim/nvidia/nemotron-3-super-120b-a12b
#      - MODEL_SONNET=nvidia_nim/meta/llama-3.3-70b-instruct
#      - MODEL=nvidia_nim/nvidia/nemotron-4-340b-instruct
#      - MODEL_SONNET=nvidia_nim/nvidia/nemotron-4-340b-instruct
#      - MODEL=nvidia_nim/meta/llama-3.1-405b-instruct
#      - MODEL_SONNET=nvidia_nim/meta/llama-3.1-405b-instruct
    restart: unless-stopped

  # PIEZA 2: La jaula de OpenCode
  ia_opencode_nvidia_runtime:
    build:
      context: .
      dockerfile: Dockerfile.runtime
    image: ia-opencode-nvidia-runtime:latest
    pull_policy: build
    container_name: ia_opencode_nvidia_runtime
    networks:
      - ia-net
    depends_on:
      - ia_proxy
# Capdrop=ALL: Elimina capacidades del kernel reduciendo drásticamente la superficie de ataque.
    cap_drop:
      - ALL
# No-new-privileges: Impide elevación de privilegios en caliente.
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
    environment:
      - ANTHROPIC_BASE_URL=http://ia_opencode_nvidia_proxy:8082 # Comunicación interna en la red docker
      # Devolvemos los tokens de éxito simulados que Claude Code necesita para desbloquear el CLI
      - CI=true
      - CLAUDE_CODE_DISABLE_ANALYTICS=true
      - CLAUDE_CODE_AUTO_COMPACT_WINDOW=80000
      - CLAUDE_CODE_THINKING_BUDGET=2048
    volumes:
      - ../../:/workspace
      - ~/.gitconfig:/home/eboe62/.gitconfig:ro
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: /home/eboe62/.npm-global/bin/claude --model claude-3-7-sonnet-20250219
